name: agent_prm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - charset-normalizer=3.3.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.77
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - ipython=8.31.0
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - numpy-base=2.0.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - readline=8.2
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchtriton=3.1.0
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - absl-py==2.1.0
    - accelerate==1.2.1
    - ai2thor==2.1.0
    - aiofiles==23.2.1
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.11
    - aiosignal==1.3.2
    - alfworld==0.4.1
    - alpaca-eval==0.6.2
    - annotated-types==0.7.0
    - anthropic==0.42.0
    - antlr4-python3-runtime==4.11.0
    - anyio==4.7.0
    - async-timeout==5.0.1
    - attrs==24.3.0
    - autoflake==2.3.1
    - beaker-py==1.32.3
    - bitsandbytes==0.45.0
    - black==24.10.0
    - blis==0.7.11
    - brotli==1.0.9
    - cachetools==5.5.0
    - catalogue==2.0.10
    - cffi==1.17.1
    - click==8.1.8
    - cloudpathlib==0.20.0
    - cloudpickle==3.1.0
    - compressed-tensors==0.8.0
    - confection==0.1.5
    - contourpy==1.3.1
    - cuda-python==12.6.2.post1
    - cycler==0.12.1
    - cymem==2.0.10
    - datasets==3.2.0
    - debugpy==1.6.7
    - decord==0.6.0
    - deepspeed==0.15.0
    - dill==0.3.8
    - diskcache==5.6.3
    - distro==1.9.0
    - docker==7.1.0
    - docker-pycreds==0.4.0
    - einops==0.8.0
    - elastic-transport==8.15.1
    - elasticsearch==8.6.2
    - et-xmlfile==2.0.0
    - evaluate==0.4.3
    - fast-downward-textworld==20.6.2
    - fastapi==0.115.6
    - ffmpy==0.5.0
    - filelock==3.13.1
    - fire==0.7.0
    - flake8==7.1.1
    - flash-attn==2.6.3
    - flask==2.1.3
    - fonttools==4.55.3
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - gguf==0.9.1
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gmpy2==2.1.2
    - google-ai-generativelanguage==0.6.10
    - google-api-core==2.24.0
    - google-api-python-client==2.156.0
    - google-auth==2.37.0
    - google-auth-httplib2==0.2.0
    - google-generativeai==0.8.3
    - googleapis-common-protos==1.66.0
    - gradio==5.9.1
    - gradio-client==1.5.2
    - grpcio==1.68.1
    - grpcio-status==1.68.1
    - h11==0.14.0
    - h5py==3.12.1
    - hashids==1.3.1
    - hf-transfer==0.1.8
    - hjson==3.1.0
    - httpcore==1.0.7
    - httplib2==0.22.0
    - httptools==0.6.4
    - httpx==0.27.2
    - huggingface-hub==0.27.0
    - idna==3.7
    - immutabledict==4.2.1
    - importlib-metadata==8.5.0
    - iniconfig==2.0.0
    - interegular==0.3.3
    - ipykernel==6.14.0
    - isort==5.13.2
    - itsdangerous==2.2.0
    - jericho==3.3.0
    - jinja2==3.1.4
    - jiter==0.8.2
    - joblib==1.4.2
    - jsonlines==4.0.0
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - kiwisolver==1.4.8
    - langcodes==3.5.0
    - langdetect==1.0.9
    - language-data==1.3.0
    - lark==1.2.2
    - litellm==1.55.12
    - llvmlite==0.43.0
    - lm-format-enforcer==0.10.6
    - marisa-trie==1.2.1
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib==3.10.0
    - mccabe==0.7.0
    - mdurl==0.1.2
    - mementos==1.3.1
    - mistral-common==1.5.1
    - mkl-fft==1.3.11
    - mkl-random==1.2.8
    - mkl-service==2.4.0
    - modelscope==1.21.0
    - more-itertools==10.5.0
    - mpmath==1.3.0
    - msgpack==1.1.0
    - msgspec==0.18.6
    - multidict==6.1.0
    - multiprocess==0.70.16
    - murmurhash==1.0.11
    - mypy-extensions==1.0.0
    - networkx==3.2.1
    - ninja==1.11.1.3
    - nltk==3.8.1
    - numba==0.60.0
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.560.30
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.1.105
    - nvidia-nvtx-cu12==12.1.105
    - open-instruct==0.0.1
    - openai==1.58.1
    - opencv-python==4.10.0.84
    - opencv-python-headless==4.10.0.84
    - openpyxl==3.1.5
    - orjson==3.10.12
    - outlines==0.0.46
    - pandas==2.2.3
    - partial-json-parser==0.2.1.1.post4
    - pathspec==0.12.1
    - patsy==1.0.1
    - peft==0.14.0
    - pillow==10.4.0
    - pip==24.3.1
    - pluggy==1.5.0
    - preshed==3.0.9
    - progressbar2==4.5.0
    - prometheus-client==0.21.1
    - prometheus-fastapi-instrumentator==7.0.0
    - propcache==0.2.1
    - proto-plus==1.25.0
    - protobuf==5.29.2
    - psutil==5.9.0
    - py-cpuinfo==9.0.0
    - pyairports==2.1.1
    - pyarrow==18.1.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pybind11==2.13.6
    - pycocotools==2.0.8
    - pycodestyle==2.12.1
    - pycountry==24.6.1
    - pycparser==2.22
    - pydantic==2.10.4
    - pydantic-core==2.27.2
    - pydub==0.25.1
    - pyflakes==3.2.0
    - pyparsing==3.2.0
    - pysocks==1.7.1
    - pytest==8.3.4
    - python-dotenv==1.0.1
    - python-multipart==0.0.20
    - python-utils==3.9.1
    - pytz==2024.2
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - ray==2.40.0
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.3
    - rich==13.9.4
    - rouge-score==0.1.2
    - rpds-py==0.22.3
    - rsa==4.9
    - ruff==0.8.4
    - safehttpx==0.1.6
    - safetensors==0.4.5
    - scikit-learn==1.6.0
    - scipy==1.14.1
    - seaborn==0.13.2
    - semantic-version==2.10.0
    - sentencepiece==0.2.0
    - sentry-sdk==2.19.2
    - setproctitle==1.3.4
    - setuptools==69.5.1
    - sglang==0.3.6.post2
    - shellingham==1.5.4
    - smart-open==7.1.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - spacy==3.7.6
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.5.0
    - starlette==0.41.3
    - sympy==1.12
    - tatsu==5.8.3
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - termcolor==2.5.0
    - textworld==1.6.1
    - thinc==8.2.5
    - threadpoolctl==3.5.0
    - tiktoken==0.7.0
    - tokenizers==0.21.0
    - tomli==2.2.1
    - tomlkit==0.13.2
    - torch==2.4.0+cu121
    - torchao==0.7.0
    - torchaudio==2.4.0+cu121
    - torchvision==0.19.0+cu121
    - tornado==6.4.2
    - tqdm==4.67.1
    - transformers==4.47.1
    - triton==3.0.0
    - trl==0.13.0
    - typer==0.15.1
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - unidic-lite==1.0.8
    - uritemplate==4.1.1
    - urllib3==2.2.3
    - uvicorn==0.34.0
    - uvloop==0.21.0
    - visdom==0.2.4
    - vllm==0.6.1.post2
    - vllm-flash-attn==2.6.1
    - wandb==0.19.1
    - wasabi==1.1.3
    - watchfiles==1.0.3
    - weasel==0.4.1
    - websocket-client==1.8.0
    - websockets==14.1
    - werkzeug==2.0.3
    - wheel==0.45.1
    - wrapt==1.17.0
    - xformers==0.0.27.post2
    - xgrammar==0.1.8
    - xxhash==3.5.0
    - yarl==1.18.3
    - zipp==3.21.0
