name: sglang
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - python=3.10.16
  - readline=8.2
  - rust=1.82.0
  - sqlite=3.45.3
  - tk=8.6.14
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.11
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - anthropic==0.42.0
    - anyio==4.7.0
    - asttokens==3.0.0
    - async-timeout==5.0.1
    - attrs==24.3.0
    - certifi==2024.12.14
    - charset-normalizer==3.4.1
    - click==8.1.8
    - cloudpickle==3.1.0
    - compressed-tensors==0.8.0
    - cuda-python==12.6.2.post1
    - datasets==3.2.0
    - decorator==5.1.1
    - decord==0.6.0
    - dill==0.3.8
    - diskcache==5.6.3
    - distro==1.9.0
    - einops==0.8.0
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - fastapi==0.115.6
    - filelock==3.16.1
    - flashinfer==0.1.6+cu121torch2.4
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - gemlite==0.4.1
    - gguf==0.10.0
    - h11==0.14.0
    - hf-transfer==0.1.8
    - httpcore==1.0.7
    - httptools==0.6.4
    - httpx==0.27.2
    - huggingface-hub==0.27.0
    - idna==3.10
    - importlib-metadata==8.5.0
    - iniconfig==2.0.0
    - interegular==0.3.3
    - ipython==8.31.0
    - jedi==0.19.2
    - jinja2==3.1.5
    - jiter==0.8.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - lark==1.2.2
    - litellm==1.55.12
    - llvmlite==0.43.0
    - lm-format-enforcer==0.10.9
    - markupsafe==3.0.2
    - matplotlib-inline==0.1.7
    - mistral-common==1.5.1
    - modelscope==1.21.0
    - mpmath==1.3.0
    - msgpack==1.1.0
    - msgspec==0.18.6
    - multidict==6.1.0
    - multiprocess==0.70.16
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - numba==0.60.0
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.560.30
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.1.105
    - openai==1.58.1
    - opencv-python-headless==4.10.0.84
    - orjson==3.10.12
    - outlines==0.0.46
    - packaging==24.2
    - pandas==2.2.3
    - parso==0.8.4
    - partial-json-parser==0.2.1.1.post4
    - pexpect==4.9.0
    - pillow==10.4.0
    - pip==24.3.1
    - pluggy==1.5.0
    - prometheus-client==0.21.1
    - prometheus-fastapi-instrumentator==7.0.0
    - prompt-toolkit==3.0.48
    - propcache==0.2.1
    - protobuf==5.29.2
    - psutil==6.1.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - py-cpuinfo==9.0.0
    - pyairports==2.1.1
    - pyarrow==18.1.0
    - pybind11==2.13.6
    - pycountry==24.6.1
    - pydantic==2.10.4
    - pydantic-core==2.27.2
    - pygments==2.18.0
    - pytest==8.3.4
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - python-multipart==0.0.20
    - pytz==2024.2
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - ray==2.40.0
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.3
    - rpds-py==0.22.3
    - safetensors==0.4.5
    - sentencepiece==0.2.0
    - setproctitle==1.3.4
    - setuptools==75.1.0
    - sglang==0.4.0.post2
    - six==1.17.0
    - sniffio==1.3.1
    - stack-data==0.6.3
    - starlette==0.41.3
    - sympy==1.13.1
    - tiktoken==0.7.0
    - tokenizers==0.21.0
    - tomli==2.2.1
    - torch==2.5.1+cu121
    - torchao==0.7.0
    - torchaudio==2.5.1+cu121
    - torchvision==0.20.1+cu121
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.47.1
    - triton==3.1.0
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - urllib3==2.3.0
    - uvicorn==0.34.0
    - uvloop==0.21.0
    - vllm==0.6.4.post1
    - watchfiles==1.0.3
    - wcwidth==0.2.13
    - websockets==14.1
    - wheel==0.44.0
    - xformers==0.0.28.post3
    - xgrammar==0.1.8
    - xxhash==3.5.0
    - yarl==1.18.3
    - zipp==3.21.0