rolloutdirs: 
  - data/alfworld/rollout/20241221-220918-iter0/leap-llm/Meta-Llama-3-8B-Instruct-sft-alfworld-iter0
  - data/alfworld/rollout/iter1-35k/rl-llm-agent/Llama-3.2-3B-Instruct-online-dpo-alfworld-iter1
  - data/alfworld/rollout/iter2-25k/rl-llm-agent/Llama-3.2-3B-Instruct-online-dpo-alfworld-iter2
max_files_per_dir: null 
outputdir: data/alfworld/prm_paired/iter0-iter1-iter2
gamma: 0.95
train_split: 0.85
delta: 0.03
