rolloutdirs: 
  - data/alfworld/rollout/iter0-10k/leap-llm/Meta-Llama-3-8B-Instruct-sft-alfworld-iter0
outputdir: data/alfworld/shaped_rewards/iter0-10k
gamma: 0.95
train_split: 0.85
shaping_constant: 3.0
critic:
  type: sglang_server
  model_id: rl-llm-agent/Llama-3.2-3B-Instruct-value-alfworld-8b-sft
  server_url: http://localhost:30030/
  prompt_template_file: prompts/alfworld/alfworld_reward_template.j2
  batch_limit: 4
  type: sglang_server
  