pos_rolloutdirs: 
  - data/alfworld/rollout/oracle-10k/leap-llm/Meta-Llama-3-8B-Instruct-sft-alfworld-iter1
neg_rolloutdirs: 
  - data/alfworld/rollout/iter0-10k/leap-llm/Meta-Llama-3-8B-Instruct-sft-alfworld-iter0
  - data/alfworld/rollout/iqlearn-iter1-10k/rl-llm-agent/Llama-3.2-3B-Instruct-online-dpo-alfworld-iqlearn-iter0
balance_pos_neg: True
policy:
  type: sglang_server
  model_id: rl-llm-agent/Llama-3.2-3B-Instruct-online-dpo-alfworld-iqlearn-iter0
  server_url: http://localhost:30010/
  prompt_template_file: prompts/alfworld/alfworld_template.j2
  temperature: 0.3
  batch_limit: 500
  verbose: 1
outputdir: data/alfworld/iqlearn/iter1
train_split: 0.85
